# generated by fastapi-codegen:
#   filename:  api.yml
#   timestamp: 2021-03-20T09:55:19+00:00

from __future__ import annotations
from typing import List, Optional
from uuid import UUID
from pydantic import BaseModel, Field


class User(BaseModel):
    id: UUID
    first_name: Field(..., minimum_length=2, maximum_length=13)
    last_name: Field(..., minimum_length=2, maximum_length=13)
    alias: Field(..., minimum_length=5, maximum_length=13)
    tag: Optional[str] = None
    author: List[UUID]
    contributor: List[UUID]
    commentor: List[UUID]
    viewer: List[UUID]


class Users(BaseModel):
    __root__: List[User] = Field(..., description='list of users')
