# generated by fastapi-codegen:
#   filename:  api.yml
#   timestamp: 2021-03-20T09:55:19+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, Query

from models.user import Users

app = FastAPI(
    version='1.0.0',
    title='Swagger for cta-backend',
    license={'name': 'MIT'},
)


@app.get('/users', response_model=Users)
def list_users(limit: int = Query(10, ge=1, le=50)) -> Users:
    """
    List all users
    """
    pass


@app.post('/users', response_model=None)
def create_user() -> None:
    """
    Create user
    """
    pass


@app.get('/pets/{pet_id}', response_model=Users)
def show_user_by_id(user_id: str = Query(..., alias='userId')) -> Users:
    """
    Info for a specific user
    """
    pass
